[package]
name = "ch569-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcell = "0.1.0"
riscv = "0.7.0"
riscv-rt = "0.8.1"

[features]
rt = []

